# Generated by Django 3.2.4 on 2021-06-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Александр Пушкин', max_length=100, verbose_name='Прочитано')),
            ],
            options={
                'ordering': ['author_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('cover', models.ImageField(upload_to='', verbose_name='Обложка')),
                ('pdf_file', models.FileField(upload_to='', verbose_name='Книга в формате PDF')),
                ('author_name', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='api.author', verbose_name='Автор')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.TextField()),
            ],
            options={
                'ordering': ['genre_name'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, max_length=100, verbose_name='Дата добавления: ')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('title', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='api.book', verbose_name='Книга')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre_name',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='api.genre', verbose_name='Жанр'),
        ),
    ]
