# Generated by Django 3.2.4 on 2021-06-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reading',
            name='book_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reading',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
